'use strict'
const { test } = require('node:test')
const assert = require('node:assert/strict')
const { execFileSync } = require('node:child_process')
const fs = require('node:fs')
const { helpers } = require('../lib')
const { createRepo, cleanup, makeShell } = require('./helpers')

test('真实分叉仓库读取双方、共同祖先、暂存及工作区差异，禁用外部驱动且不修改仓库', async () => {
  const dir = createRepo()
  const git = (...args) => execFileSync('git', args, { cwd: dir, encoding: 'utf8' }).trim()
  try {
    git('switch', '-c', 'remote')
    fs.writeFileSync(dir + '/a.txt', 'remote value\n')
    git('commit', '-am', 'remote change')
    git('switch', 'main')
    fs.writeFileSync(dir + '/a.txt', 'local value\n')
    git('commit', '-am', 'local change')
    fs.writeFileSync(dir + '/staged.txt', 'staged content\n')
    git('add', 'staged.txt')
    fs.writeFileSync(dir + '/a.txt', 'uncommitted content\n')
    fs.writeFileSync(dir + '/new.txt', 'untracked content\n')
    const driver = dir + '/.git/diff-driver'
    fs.writeFileSync(driver, '#!/bin/sh\ntouch "' + dir + '/driver-ran"\n', { mode: 0o700 })
    git('config', 'diff.external', driver)
    git('config', 'diff.test.textconv', driver)
    fs.writeFileSync(dir + '/.git/info/attributes', '*.txt diff=test\n')
    const repo = new helpers.GitRepositoryService(makeShell(dir))
    const before = await repo.proposalSnapshot(dir)
    const compare = (base, target, mergeBase = false) => repo.getDiff(dir, undefined, false, undefined, undefined, { base, target, mergeBase })
    const diff = await compare('main', 'remote')
    assert.equal(diff.ok, true)
    assert.match(diff.data.diff, /-local value\n\+remote value/)
    assert.match((await compare('main', 'remote', true)).data.diff, /-hello\n\+remote value/)
    assert.match((await compare('remote', 'main', true)).data.diff, /-hello\n\+local value/)
    assert.match((await repo.getDiff(dir, 'a.txt', false)).data.diff, /\+uncommitted content/)
    assert.match((await repo.getDiff(dir, undefined, true)).data.diff, /\+staged content/)
    assert.match((await repo.getDiff(dir, 'new.txt', false)).data.diff, /\+untracked content/)
    assert.equal(fs.existsSync(dir + '/driver-ran'), false)
    assert.equal(await repo.proposalSnapshot(dir), before)
    for (const ref of ['missing', '--output=driver-ran', 'HEAD; touch driver-ran', '$(touch driver-ran)', null]) {
      assert.equal((await compare(ref, 'HEAD')).ok, false)
    }
    assert.equal((await repo.getDiff(dir, '../outside', false)).ok, false)
    assert.equal((await repo.getDiff(dir, undefined, true, undefined, undefined, { base: 'main', target: 'remote' })).ok, false)
    assert.equal(fs.existsSync(dir + '/driver-ran'), false)
    fs.writeFileSync(dir + '/large.txt', 'x'.repeat(210000))
    const large = await repo.getDiff(dir, 'large.txt', false)
    assert.equal(large.ok, true)
    assert.equal(large.data.truncated, true)
    assert.equal(large.data.diff.length, 200000)
  } finally { cleanup(dir) }
})
